// <copyright file="GPGSIds.cs" company="Google Inc.">
// Copyright (C) 2015 Google Inc. All Rights Reserved.
//
//  Licensed under the Apache License, Version 2.0 (the "License");
//  you may not use this file except in compliance with the License.
//  You may obtain a copy of the License at
//
//  http://www.apache.org/licenses/LICENSE-2.0
//
//  Unless required by applicable law or agreed to in writing, software
//  distributed under the License is distributed on an "AS IS" BASIS,
//  WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//  See the License for the specific language governing permissions and
//    limitations under the License.
// </copyright>

///
/// This file is automatically generated DO NOT EDIT!
///
/// These are the constants defined in the Play Games Console for Game Services
/// Resources.
///


public static class GPGSIds
{
        public const string event_breaking_triple_digits = "CgkImtHB9JsCEAIQBw"; // <GPGSID>
        public const string event_understanding_the_puzzle = "CgkImtHB9JsCEAIQBQ"; // <GPGSID>
        public const string event_true_expert = "CgkImtHB9JsCEAIQEg"; // <GPGSID>
        public const string achievement = "CgkImtHB9JsCEAIQFQ"; // <GPGSID>
        public const string achievement_10 = "CgkImtHB9JsCEAIQHw"; // <GPGSID>
        public const string event_puzzle_enthusiast = "CgkImtHB9JsCEAIQCQ"; // <GPGSID>
        public const string event_on_the_verge_of_legend = "CgkImtHB9JsCEAIQEw"; // <GPGSID>
        public const string event_halfway_to_the_top = "CgkImtHB9JsCEAIQDQ"; // <GPGSID>
        public const string achievement_2 = "CgkImtHB9JsCEAIQFg"; // <GPGSID>
        public const string achievement_3 = "CgkImtHB9JsCEAIQFw"; // <GPGSID>
        public const string leaderboard_stageclear = "CgkImtHB9JsCEAIQAg"; // <GPGSID>
        public const string achievement_6 = "CgkImtHB9JsCEAIQGw"; // <GPGSID>
        public const string achievement_7 = "CgkImtHB9JsCEAIQHA"; // <GPGSID>
        public const string achievement_4 = "CgkImtHB9JsCEAIQGA"; // <GPGSID>
        public const string achievement_5 = "CgkImtHB9JsCEAIQGg"; // <GPGSID>
        public const string achievement_8 = "CgkImtHB9JsCEAIQHQ"; // <GPGSID>
        public const string achievement___777 = "CgkImtHB9JsCEAIQIQ"; // <GPGSID>
        public const string event_the_end_in_sight = "CgkImtHB9JsCEAIQEA"; // <GPGSID>
        public const string achievement_12 = "CgkImtHB9JsCEAIQIg"; // <GPGSID>
        public const string event_cant_stop_now = "CgkImtHB9JsCEAIQCg"; // <GPGSID>
        public const string event_rookies_start = "CgkImtHB9JsCEAIQAw"; // <GPGSID>
        public const string event_legend_of_the_puzzle = "CgkImtHB9JsCEAIQFA"; // <GPGSID>
        public const string event_jackpot = "CgkImtHB9JsCEAIQEQ"; // <GPGSID>
        public const string event_an_ominous_feeling = "CgkImtHB9JsCEAIQDA"; // <GPGSID>
        public const string achievement_11 = "CgkImtHB9JsCEAIQIA"; // <GPGSID>
        public const string event_tile_master = "CgkImtHB9JsCEAIQDw"; // <GPGSID>
        public const string event_path_of_the_expert = "CgkImtHB9JsCEAIQDg"; // <GPGSID>
        public const string event_first_steps = "CgkImtHB9JsCEAIQBA"; // <GPGSID>
        public const string event_became_an_intermediate = "CgkImtHB9JsCEAIQBg"; // <GPGSID>
        public const string event_befriending_the_tiles = "CgkImtHB9JsCEAIQCA"; // <GPGSID>
        public const string achievement_100 = "CgkImtHB9JsCEAIQGQ"; // <GPGSID>
        public const string event_muscle_memory = "CgkImtHB9JsCEAIQCw"; // <GPGSID>
        public const string achievement_13 = "CgkImtHB9JsCEAIQIw"; // <GPGSID>
        public const string achievement_9 = "CgkImtHB9JsCEAIQHg"; // <GPGSID>

}

